### ISSUE TITLE
Updates for Gatsby branch

### ISSUE THREAD

**Issue by eumentis-mehul** [eumentis-cloud/ec-website#14]
- [x] In current website, when a section is selected in main menu, a small white triangle points towards the selected menu item. This is not present in current version.
- [x] On Home page, in section 'Top Clients' country name gets hidden by 'Eumentis Cloud' badge in bottom bar.
- [x] Discuss design of statement "At Eumentis, we are genuine, of good intellect, have great reasoning and a sound mind; which is portrayed by our name." in About Us > About Eumentis. 
- [x] Our Team: Photos are cropped and appear blurry as compared to original website. 

- [x] Ritesh and Ruchika information missing. Mobile + Web Developer

- [x] Since 'Our Team' section is also dynamic, should a csv be prepared for this data as well?

- [x] Discuss if we should add 'Our Services' section. 

- [x] Remove hover effect from images on all pages except 'Our Work'

- [x] Discuss design of 'Contact Us' page  
- [x] Overall website: Discuss all the fonts used and prepare a styling guide for the same to ensure consistency

_- [ ] Replace Pritesh Sikchi with Manohar Lahoti,_

**Comment by eumentis-aditya** [comment]
- [ ] Create a 404 Page template design

**Comment by eumentis-aditya** [comment]
> * [ ]  Shift 'Our Work' to the left of 'About Us'

Resolved header tab position

**Comment by eumentis-aditya** [comment]
- [ ] Problem and solution logo appearing different on S2C details page
- [ ] Fix Our Work page cards appearing to stick each other
- [ ] temporarily hide testimonial section on details pages
- [ ] Display project description below title under details page
- [ ] Zoom out background image from details page to fill up empty space
- [ ] Don't highlight VendR and Drona cards and discard details page for them
- [ ] Update the details page by populating the data from corporate profile
- [ ] Rename "Videos" to "Demo Videos"
- [ ] remove the quotes from the message for internal apps
- [ ] Redesign the first fold of the details page with balsamiq design
- [ ] Design career page

**Comment by eumentis-aditya** [comment]
Fix: Problem and solution logo appearing different on S2C details page
-> I'm unable to find the fix for colour changes in different pages

**Comment by eumentis-aditya** [comment]
- [ ] create a context to pass location prop down to all children

**Comment by eumentis-mehul** [comment]
- [ ] Can we have a fixed height for cards. And not height based on content, which is making some card bigger than the others. Refer attached screenshot.
![Screenshot from 2020-11-05 10-35-28](https://user-images.githubusercontent.com/67255645/98200122-e8e47e00-1f52-11eb-8594-bc9531086373.png)
![Screenshot from 2020-11-05 10-35-22](https://user-images.githubusercontent.com/67255645/98200125-eaae4180-1f52-11eb-8834-d42a27527a02.png)

- [ ] New assets for 'Problem' & 'Solution'

- [ ] On 'Our Work' page, convert mouse pointer to hand only when hovering over a card which is a hyperlink. Meaning, no hand pointer when mouse is pointed to empty space b/w cards + when mouse is pointed on cards that are not clickable.

- [ ] The alignment of 'Demo Video' and 'Links' sections is off. For one page, text was hidden behind 'Solution' card. Refer screenshots. Left align heading 'Demo Videos' and 'Links'. Then left align, 1st video link, and 1st button link (which could be 'launch website', play store or app store button depending upon project). If no button, then left align the text message (mobile apps distributed internally etc.) with heading.
![Screenshot from 2020-11-05 10-47-19](https://user-images.githubusercontent.com/67255645/98200807-66f55480-1f54-11eb-8eb1-4ddfac00e3b7.png)
![Screenshot from 2020-11-05 10-47-09](https://user-images.githubusercontent.com/67255645/98200812-678deb00-1f54-11eb-966a-0f26bc89a5db.png) 
![Screenshot from 2020-11-05 10-47-31](https://user-images.githubusercontent.com/67255645/98200803-65c42780-1f54-11eb-9b6f-0e9ee1f5bc0c.png)

### Career section updates

- [ ] Remove the 'Careers at Eumentis Cloud' header from both main career page and child pages.

- [ ] Update text "Apply for software development positions with Eumentis Informatics Pvt. Ltd." to "Apply for following available positions with Eumentis Informatics Pvt. Ltd."

- [ ] When a job description page is open (the child pages), on top left show a breadcrumb menu (like we have done in Project details page; same position). For e.g. 'Careers / Technical Lead'. Keep styling such that it is clearly visible over the current image.

- [ ] Reduce/remove empty space after 'Apply' button on job description page
