### ISSUE TITLE
"The mobile apps are distributed internally" - Message shown for projects where no app was developed

### ISSUE THREAD

**Issue by eumentis-mehul** [eumentis-cloud/ec-website#15]
Current logic is that if Play store or app store link is not present then show this message - "The mobile apps are distributed internally". But this is not true for all cases. 
In some projects no app was developed. Will have to show relevant message there or show no message there as apps were not part of the project. 

In Corporate profile, "The mobile apps are distributed internally" message is present for only those projects where apps were developed but not uploaded to app or play store.

**Comment by eumentis-mehul** [comment]
Gauri & RST also do not have mobile apps.

Halagig - different message altogether "The mobile apps are under development and yet to be deployed on app stores"

**Comment by eumentis-aditya** [comment]
resolved this issue
