### ISSUE TITLE
Update design of problems & solutions card

### ISSUE THREAD

**Issue by eumentis-mehul** [eumentis-cloud/ec-website#16]
Edited css in chrome to get to a suitable design. Couldn't figure out how to edit bootstraps' scss files lest I spoil some other component of the website. 

Attaching screenshots for the parameters that I edited to get to the desired design. 
![Screenshot from 2020-11-26 23-59-07](https://user-images.githubusercontent.com/67255645/100507440-62a70a80-3193-11eb-988e-491dcf3da0fa.png)

**Comment by eumentis-aditya** [comment]
designed the same as attached in the screenshot
