### ISSUE TITLE
Misalignment of icons on project details page

### ISSUE THREAD

**Issue by eumentis-mehul** [eumentis-cloud/ec-website#18]
Product Authenticity Verification Platform project details page, the app store and play store icons are misaligned.
Refer screenshot. Could be because of screen size.
![Screenshot from 2020-11-28 18-00-55](https://user-images.githubusercontent.com/67255645/100515713-1b754580-31a4-11eb-8542-8e689a6bf9d7.png)

**Comment by eumentis-aditya** [comment]
resolved this fix
